# Training pipeline
epochs: 3000
batch_size: 16
strategy: "auto"
num_workers: 6
gradient_clip_val: 5.0
precision: "16-mixed"
test_batch_size: 32


input_resolution: [512, 512]

normalize: false
knn_eval_frequency: 20
patience: 1000
monitor: "val/loss"

input_resolution: [512, 512]

# Model parameters
model_params:
  lr: 1.5e-4 # base learning rate used during pretraining in the paper.
  min_lr: 1e-7 # small learning rate that's linearly ramped up
  img_size: 512
  mask_ratio: 0.75
  warmup_steps: 1 # For MAE this represents the number of warmup epochs
  in_chans: 2
  # Vit-B settings
  vit_type: "t"
  patch_size: 16
  reg_tokens: 0
  #reg_tokens: 4 # Used because in the paper "VISION TRANSFORMERS NEED REGISTERS" they get 
  # maximum segmentation mIoU with 4 register tokens



# Model checkpoint
# ckpt_path: './checkpoints/pretrain_vit_dino_example.ckpt'
# ckpt_path: './checkpoints/pretrain_fastervit0_mae_example.ckpt'