# Store all tracking, and dataset parameters unrelated to pipeline and model 
# optimization.

# Experiment tracking
# Current experiment number
experiment_n: 8
# MLFlow tracking uri
tracking_uri: "http://localhost:5000"

# Dataset variables
crop_size: 512 

data_path: "./datasets/MNIST/pretrain/"
eval_data_path: "./datasets/MNIST/finetune/"

classes: ["class_0", "class_1"]

# Monitoring and logging
seed: 42
monitor: "val/loss"
patience: 50
log_every_n: 2
check_val_every_n: 10