# Experiment Tracking
# MLFlow Experiment name
name: aoi-finetune-fastervit-ibot

# Training pipeline
epochs: 100
batch_size: 8
strategy: auto
num_workers: 1
gradient_clip_val: 5.0
precision: "16-mixed"
accumulate_grad_batches: 1

input_resolution: [512, 512]
model: "fastervit"
encoder_model: "ibot" # Options: "ibot", "mae"

# Model parameters
model_params:
  mesa_lmbda: 3.0
  mesa_finetune: False
  num_classes: 2 # change with the number of classes in your dataset

  ## Ignore this part, without scheduler 
  warmup_steps: 5 # For MAE, Warm-up epochs
  min_lr: 5.0e-7
  weight_decay: 5.0e-2
  lr: 5.0e-4
  layer_decay: 0.75
  use_annealing_lr: True
  use_decay_lr: True

  img_size: 512  # input image size for fixed resolution models

  # Encoder settings
  patch_size: 16
  reg_tokens: 0
  decoder_cls: "upernet"
  freeze_encoder: False
  encoder_type: "fastervit"

# Vit-t with small patches
encoder_ckpt_path: './checkpoints/pretrain_fastervit0_ibot.ckpt'
encoder_ckpt_model_params: './configs/pretrain/pretrain_fastervit_0_ibot_model_config.yml'
