# Store all tracking, and dataset parameters unrelated to pipeline and model 
# optimization.

# Experiment tracking
# Current experiment number
experiment_n: 2 
# MLFlow tracking uri
tracking_uri: "http://localhost:5000"

# Dataset variables
crop_size: 512
classes: ["class_0", "class_1"]
data_path: "./datasets/MNIST/pretrain/"

# Monitoring and logging
seed: 42
monitor: "val/loss"
patience: 500
log_every_n: 40
check_val_every_n: 3
